#!/bin/sh

echo "run readmeGenerator before commit"

python3 readmeGenerator.py

# 检查工作区中是否有未暂存的变更
if git diff --exit-code --name-only | grep -q "README.md"; then
    echo "Changes detected in README.md. Please review the changes before committing."
    exit 1
fi